name: "Comprueba la existencia de historias de usuario"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[1234567].md'

jobs:
  user_story_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v1
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Busca historias de usuario
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            console.log(ghRepoMatch)


